image: 'rust:latest'

stages:
 - build
 - package

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

before_script:
  - apt-get update -y
  - apt-get install libasound2-dev libxcb-xrm-dev libxcb-xfixes0-dev libxcb-shape0-dev -y

build:
  stage: build
  script:
    - rustc --version
    - cargo --version
    - cargo build --release
  artifacts:
    paths:
    - target/release/tower

package:
  stage: pacakge
  script:
  -  tar -czvf tower.$CI_COMMIT_SHA.tar.gz config -C target/release tower
  artifacts:
    paths:
    - tower.$CI_COMMIT_SHA.tar.gz
    
#test2:
#  stage: test2
#  script:
#    - echo kikoo

#pages:
#  stage: doc
#  script:
#    - cargo doc --no-deps
#    - mv target/doc public
#    - echo '<meta http-equiv="refresh" content="0; url={{ LIBRARY NAME }}">' > public/index.html
#  artifacts:
#    paths:
#      - public
#  only:
#    - master

cache:
  paths:
    - apt/
    - cargo/
    - target/
