[package]
name = "tower"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
image = "0.22.3"
cgmath = "0.17.0"
uuid = "0.7.0"
[dependencies.amethyst]
version = "0.13"
features = ["vulkan"]
